### ISSUE TITLE
jekyll-action does not copy CNAME file to gh-pages

### ISSUE THREAD

**Issue by martinmorando** [criptowiki/criptowiki#15]

**Comment by martinmorando** [comment]
It's a problem that many have encountered; there are [several open and closed issues on the repository](https://github.com/helaili/jekyll-action/issues?q=cname). Issue [98](https://github.com/helaili/jekyll-action/issues/98), opened 1 month ago, describes it, and [there is a pull request (102) addressing this](https://github.com/helaili/jekyll-action/pull/102). On the other hand, the maintainer has [stated last year that this has already been solved](https://github.com/helaili/jekyll-action/issues/57#issuecomment-699807810). Finding out if it's a repository or documentation problem.

**Comment by martinmorando** [comment]
Built the Jekyll site in localhost using `bundle exec jekyll build` and found out that Jekyll was the one ignoring the CNAME file, not jekyll-action.

Solved by [forcing the inclusion of CNAME file](https://github.com/criptowiki/criptowiki/commit/9b7bb84d840007f172b034a83d2e5ce65630e815), following [Jekyll configuration options](https://jekyllrb.com/docs/configuration/options/).

 Issue solved but, at the moment, it is not clear why some Jekyll sites must make it explicit and others not.

**Comment by viniciuspereiras** [comment]
> Built the Jekyll site in localhost using `bundle exec jekyll build` and found out that Jekyll was the one ignoring the CNAME file, not jekyll-action.
> 
> Solved by [forcing the inclusion of CNAME file](https://github.com/criptowiki/criptowiki/commit/9b7bb84d840007f172b034a83d2e5ce65630e815), following [Jekyll configuration options](https://jekyllrb.com/docs/configuration/options/).
> 
> Issue solved but, at the moment, it is not clear why some Jekyll sites must make it explicit and others not.

Thanks for that, I  think that worked for me 👍

**Comment by erin-bristow** [comment]
> Built the Jekyll site in localhost using `bundle exec jekyll build` and found out that Jekyll was the one ignoring the CNAME file, not jekyll-action.
> 
> Solved by [forcing the inclusion of CNAME file](https://github.com/criptowiki/criptowiki/commit/9b7bb84d840007f172b034a83d2e5ce65630e815), following [Jekyll configuration options](https://jekyllrb.com/docs/configuration/options/).
> 
> Issue solved but, at the moment, it is not clear why some Jekyll sites must make it explicit and others not.

@martinmorando Also worked for me! Thanks so much, that was a frustrating issue :)
