### ISSUE TITLE
Felicitar por el proyecto

### ISSUE THREAD

**Issue by SidVal** [criptowiki/criptowiki#22]
Esto no es un bug, ni issue, pero no encontré info de contacto para saludar a los creadores.

Estoy recopilando wikis y sitios web que expandan el conocimiento en español sobre criptomonedas.
Así llegué aca.

No entendí porque el sitio está en español y todos los issues en inglés ;) 
Pero más allá de todo, éxito en este proyecto! Que no decaiga!!! 
Ya lo sumé a mi lista de recursos.

**Comment by martinmorando** [comment]
¡Gracias por tu mensaje! 

El código está separado del contenido (en lo posible). El código y los issues están en inglés, y el contenido está en español. Alguien que no sabe español o no conoce el contenido pero sabe programar y sabe inglés elemental puede mejorar el código o usarlo. Además, la idea es después [traducirlo a otros idiomas](https://github.com/criptowiki/criptowiki/issues/1). Es cierto que hay issues en inglés sobre contenido que actualmente está solo en español pero preferí mantener los todos issues en inglés para que sea consistente, aunque esto podría cambiar. 

Estuve explorando otras ideas, algunas para incorporar a este proyecto. La semana que viene termino de rendir exámenes y seguiré mejorándolo. Ante cualquier duda, encontrarás información de contacto [en esta página](https://cripto.wiki/acerca-de/) y podés enterarte de cualquier novedad en [Twitter](https://twitter.com/criptowiki).
